package com.mycompany.simulador;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.util.ArrayList;
import javax.swing.*;

/**
 *
 * @author JORGE SOLANO && SARA SIERRA
 */
public class SimuladorHome extends javax.swing.JFrame {

    /**
     * Creates new form SimuladorHome
     */
    public SimuladorHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        AñadirDispositivoPanel = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        verRedes = new javax.swing.JList<>();
        visualizarRedes = new javax.swing.JButton();
        EliminarRedes = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        visualizarDispositivos = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        verDispositivos = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        vernodo = new javax.swing.JList<>();
        redVisualizar = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        enviarM = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        actualizarMensajes = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        MensajesEnviadosVer = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        redOrigen = new javax.swing.JComboBox<>();
        redDestino = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        mensajeEnviar = new javax.swing.JTextArea();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        EnviarPaquete = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        dispositivoOrigen = new javax.swing.JComboBox<>();
        dispositivoDestino = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        nombreDispositivo = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        direccionIPDispositivo = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        direccionMACDispositivo = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        tipoDispositivo = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        aplicar_creacion_dispositivo = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        redesDisponibles = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        transmisionRed = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        accesoRed = new javax.swing.JTextField();
        aplicar_creacion_red = new javax.swing.JButton();
        estandarRed = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        nombreRed = new javax.swing.JTextField();
        velocidadRed = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(verRedes);

        visualizarRedes.setBackground(new java.awt.Color(204, 255, 204));
        visualizarRedes.setText("Actualizar");
        visualizarRedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarRedesActionPerformed(evt);
            }
        });

        EliminarRedes.setBackground(new java.awt.Color(255, 204, 204));
        EliminarRedes.setText("Eliminar");
        EliminarRedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarRedesActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel13.setText("AQUÍ PODRÁS VER LOS REDES EXISTENTES");

        visualizarDispositivos.setBackground(new java.awt.Color(204, 255, 204));
        visualizarDispositivos.setText("Dispositvos");
        visualizarDispositivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarDispositivosActionPerformed(evt);
            }
        });

        jScrollPane5.setViewportView(verDispositivos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(visualizarRedes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(visualizarDispositivos)
                        .addGap(51, 51, 51)
                        .addComponent(EliminarRedes))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(visualizarRedes)
                    .addComponent(visualizarDispositivos)
                    .addComponent(EliminarRedes))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        AñadirDispositivoPanel.addTab("REDES", jPanel2);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Estrella");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Anillo");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Bus");

        jLabel15.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel15.setText("VISUALIZA TUS REDES");

        jButton4.setText("Ver");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(vernodo);

        redVisualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                redVisualizarMouseClicked(evt);
            }
        });

        jLabel26.setText("Red");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane4)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(redVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addContainerGap(16, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel15)
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton2)
                    .addComponent(jButton4)
                    .addComponent(redVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        AñadirDispositivoPanel.addTab("VISUALIZAR", jPanel5);

        enviarM.setBackground(new java.awt.Color(255, 204, 204));
        enviarM.setText("Cerrar");
        enviarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarMActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel11.setText("VER MENSAJES ENVIADOS");

        actualizarMensajes.setBackground(new java.awt.Color(204, 255, 204));
        actualizarMensajes.setText("Actualizar");
        actualizarMensajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarMensajesActionPerformed(evt);
            }
        });

        MensajesEnviadosVer.setColumns(20);
        MensajesEnviadosVer.setRows(5);
        jScrollPane2.setViewportView(MensajesEnviadosVer);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(actualizarMensajes)
                .addGap(108, 108, 108)
                .addComponent(enviarM)
                .addGap(75, 75, 75))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel11))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enviarM)
                    .addComponent(actualizarMensajes))
                .addContainerGap(216, Short.MAX_VALUE))
        );

        AñadirDispositivoPanel.addTab("MENSAJE", jPanel4);

        redOrigen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                redOrigenMouseClicked(evt);
            }
        });
        redOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redOrigenActionPerformed(evt);
            }
        });

        redDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos" }));
        redDestino.setToolTipText("");
        redDestino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                redDestinoMouseClicked(evt);
            }
        });
        redDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redDestinoActionPerformed(evt);
            }
        });

        jLabel6.setText("Red origen");

        jLabel7.setText("Red Destino");

        jLabel8.setText("Mensaje");

        mensajeEnviar.setColumns(20);
        mensajeEnviar.setRows(5);
        jScrollPane3.setViewportView(mensajeEnviar);

        jLabel9.setText("Tamaño de paquete");

        EnviarPaquete.setBackground(new java.awt.Color(204, 255, 204));
        EnviarPaquete.setText("Enviar");
        EnviarPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarPaqueteActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel14.setText("ENVÍA TU PAQUETE");

        dispositivoOrigen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dispositivoOrigenMouseClicked(evt);
            }
        });
        dispositivoOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispositivoOrigenActionPerformed(evt);
            }
        });

        dispositivoDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos" }));
        dispositivoDestino.setToolTipText("");
        dispositivoDestino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dispositivoDestinoMouseClicked(evt);
            }
        });
        dispositivoDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispositivoDestinoActionPerformed(evt);
            }
        });

        jLabel10.setText("Dispositivo origen");

        jLabel25.setText("Dispositivo Destino");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6))
                                        .addGap(37, 37, 37)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(redDestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(redOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel25)
                                            .addComponent(jLabel10)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dispositivoDestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dispositivoOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(EnviarPaquete)
                        .addGap(82, 82, 82))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel14)
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(redOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(redDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dispositivoOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dispositivoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))))
                .addGap(39, 39, 39)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EnviarPaquete)
                .addGap(64, 64, 64))
        );

        AñadirDispositivoPanel.addTab("ENVIAR", jPanel3);

        nombreDispositivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreDispositivoActionPerformed(evt);
            }
        });

        jLabel20.setText("Dirección IP");

        jLabel21.setText("Dirección MAC");

        jLabel22.setText("Tipo de dispositivo");

        tipoDispositivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PC", "Impresora", "Fax", "Router" }));
        tipoDispositivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoDispositivoActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel23.setText("AÑADIR DISPOSITIVO");

        jLabel24.setText("Nombre");

        aplicar_creacion_dispositivo.setBackground(new java.awt.Color(204, 255, 204));
        aplicar_creacion_dispositivo.setText("Aplicar");
        aplicar_creacion_dispositivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aplicar_creacion_dispositivoActionPerformed(evt);
            }
        });

        jLabel27.setText("Red");

        redesDisponibles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                redesDisponiblesMouseClicked(evt);
            }
        });
        redesDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redesDisponiblesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel23))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(aplicar_creacion_dispositivo)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel21)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(51, 51, 51)))
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(redesDisponibles, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nombreDispositivo)
                                    .addComponent(direccionIPDispositivo)
                                    .addComponent(direccionMACDispositivo)
                                    .addComponent(tipoDispositivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(6, 6, 6))))
                .addContainerGap(225, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel20)
                        .addGap(80, 80, 80))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(nombreDispositivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(direccionIPDispositivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(direccionMACDispositivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tipoDispositivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(redesDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(15, 15, 15)
                .addComponent(aplicar_creacion_dispositivo)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        AñadirDispositivoPanel.addTab("AÑADIR DISPOSITIVO", jPanel6);

        jLabel1.setText("Velocidad de transmisión: ");

        jLabel3.setText("Estándar");

        jLabel4.setText("Soporte de transmisión");

        transmisionRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transmisionRedActionPerformed(evt);
            }
        });

        jLabel5.setText("Control de acceso");

        accesoRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accesoRedActionPerformed(evt);
            }
        });

        aplicar_creacion_red.setBackground(new java.awt.Color(204, 255, 204));
        aplicar_creacion_red.setText("Aplicar");
        aplicar_creacion_red.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aplicar_creacion_redActionPerformed(evt);
            }
        });

        estandarRed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IEEE 802.3 (Ethernet)", "IEEE 802.3ab (Gigabit Ethernet)", "IEEE 802.3u (Fast Ethernet)" }));
        estandarRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estandarRedActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel12.setText("AÑADIR RED");

        jLabel16.setText("Nombre");

        nombreRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreRedActionPerformed(evt);
            }
        });

        velocidadRed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10mb", "100mb", "1000mb" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(93, 93, 93)
                            .addComponent(nombreRed, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addGap(83, 83, 83)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(accesoRed)
                                .addComponent(transmisionRed)
                                .addComponent(velocidadRed, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(estandarRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(aplicar_creacion_red)))
                .addContainerGap(225, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel12)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(nombreRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(estandarRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(velocidadRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transmisionRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accesoRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(aplicar_creacion_red)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        AñadirDispositivoPanel.addTab("CREAR RED", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AñadirDispositivoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AñadirDispositivoPanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void transmisionRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transmisionRedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transmisionRedActionPerformed

    private void accesoRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accesoRedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accesoRedActionPerformed

    private void estandarRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estandarRedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estandarRedActionPerformed

    private void redOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_redOrigenActionPerformed

    private void redDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_redDestinoActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void enviarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enviarMActionPerformed

    private void nombreRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreRedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreRedActionPerformed

    private void nombreDispositivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreDispositivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreDispositivoActionPerformed

    private void tipoDispositivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoDispositivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoDispositivoActionPerformed

    private void dispositivoOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dispositivoOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dispositivoOrigenActionPerformed

    private void dispositivoDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dispositivoDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dispositivoDestinoActionPerformed

    private void aplicar_creacion_redActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplicar_creacion_redActionPerformed
        // TODO add your handling code here:
        Red red = new Red(nombreRed.getText(), estandarRed.getSelectedItem().toString(), velocidadRed.getSelectedItem().toString(), transmisionRed.getText(), accesoRed.getText());
        redes.add(red);
        JOptionPane.showMessageDialog(null, "Se ha creado correctamente la red");
    }//GEN-LAST:event_aplicar_creacion_redActionPerformed

    private void aplicar_creacion_dispositivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplicar_creacion_dispositivoActionPerformed
        // TODO add your handling code here:
        Dispositivo dispositivo = new Dispositivo(nombreDispositivo.getText(), tipoDispositivo.getSelectedItem().toString(), direccionIPDispositivo.getText(), direccionMACDispositivo.getText());
        for (Red r : redes) {
            if (r.getNombre() == redesDisponibles.getSelectedItem().toString()) {
                r.AgregarDispositivo(dispositivo);
            }
        }
        JOptionPane.showMessageDialog(null, "Se ha instalado correctamente el dispositivo");
    }//GEN-LAST:event_aplicar_creacion_dispositivoActionPerformed

    private void redesDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redesDisponiblesActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_redesDisponiblesActionPerformed

    private void visualizarRedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarRedesActionPerformed
        // TODO add your handling code here:
        DefaultListModel<String> redesLocales = new DefaultListModel<>();
        for (Red r : redes) {
            redesLocales.addElement(r.getNombre());
        }
        verRedes.setModel(redesLocales);
    }//GEN-LAST:event_visualizarRedesActionPerformed

    private void EliminarRedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarRedesActionPerformed
        // TODO add your handling code here:
        boolean eliminado = false;

        try {
            for (Red r : redes) {
                if (r.getNombre() == verRedes.getSelectedValue()) {
                    eliminado = redes.remove(r);
                }
            }
        } catch (Exception e) {
            if (eliminado) {
                JOptionPane.showMessageDialog(null, "Se ha eliminado correctamente la red");
            } else {
                JOptionPane.showMessageDialog(null, "No se ha eliminado la red");
            }
        }
    }//GEN-LAST:event_EliminarRedesActionPerformed

    private void visualizarDispositivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarDispositivosActionPerformed
        // TODO add your handling code here:
        DefaultListModel<String> DispositivosLocales = new DefaultListModel<>();
        for (Red r : redes) {
            for (Dispositivo d : r.getDispositivos()) {
                DispositivosLocales.addElement(d.getId());
            }
        }
        verDispositivos.setModel(DispositivosLocales);
    }//GEN-LAST:event_visualizarDispositivosActionPerformed

    private void redesDisponiblesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redesDisponiblesMouseClicked
        // TODO add your handling code here:
        RefrescarRedes(redesDisponibles);

    }//GEN-LAST:event_redesDisponiblesMouseClicked

    private void redOrigenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redOrigenMouseClicked
        // TODO add your handling code here:
        RefrescarRedes(redOrigen);
    }//GEN-LAST:event_redOrigenMouseClicked

    private void redDestinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redDestinoMouseClicked
        // TODO add your handling code here:
        RefrescarRedes(redDestino);
        redDestino.addItem("Todos");
    }//GEN-LAST:event_redDestinoMouseClicked

    private void redVisualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redVisualizarMouseClicked
        // TODO add your handling code here:
        RefrescarRedes(redVisualizar);
    }//GEN-LAST:event_redVisualizarMouseClicked

    private void dispositivoOrigenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dispositivoOrigenMouseClicked
        // TODO add your handling code here:
        dispositivoOrigen.removeAllItems();
        for (Red r : redes) {
            if (redOrigen.getSelectedItem() == r.getNombre()) {
                for (Dispositivo d : r.getDispositivos()) {
                    dispositivoOrigen.addItem(d.getTipoDispositivo() + ": " + d.getId());
                }
            }
        }
    }//GEN-LAST:event_dispositivoOrigenMouseClicked

    private void dispositivoDestinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dispositivoDestinoMouseClicked
        // TODO add your handling code here:
        dispositivoDestino.removeAllItems();
        for (Red r : redes) {
            if (redDestino.getSelectedItem() == r.getNombre()) {
                for (Dispositivo d : r.getDispositivos()) {
                    dispositivoDestino.addItem(d.getTipoDispositivo() + ": " + d.getId());
                }
            }
        }

    }//GEN-LAST:event_dispositivoDestinoMouseClicked

    private void EnviarPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarPaqueteActionPerformed
        // TODO add your handling code here:
        mensajesEnviados += "++++" + dispositivoOrigen.getSelectedItem().toString() + ":        " + mensajeEnviar.getText() + "\n";
        JOptionPane.showMessageDialog(null, "El mensaje fue enviado Correctamente");
    }//GEN-LAST:event_EnviarPaqueteActionPerformed

    private void actualizarMensajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarMensajesActionPerformed
        // TODO add your handling code here:
        MensajesEnviadosVer.setText(mensajesEnviados);
    }//GEN-LAST:event_actualizarMensajesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimuladorHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimuladorHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimuladorHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimuladorHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimuladorHome().setVisible(true);
            }
        });
    }

    public void RefrescarRedes(JComboBox<String> redesDisponibles) {
        redesDisponibles.removeAllItems();
        for (Red r : redes) {
            redesDisponibles.addItem(r.getNombre());
        }
    }
    static String mensajesEnviados = "";
    static ArrayList<Red> redes = new ArrayList();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane AñadirDispositivoPanel;
    private javax.swing.JButton EliminarRedes;
    private javax.swing.JButton EnviarPaquete;
    private javax.swing.JTextArea MensajesEnviadosVer;
    private javax.swing.JTextField accesoRed;
    private javax.swing.JButton actualizarMensajes;
    private javax.swing.JButton aplicar_creacion_dispositivo;
    private javax.swing.JButton aplicar_creacion_red;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField direccionIPDispositivo;
    private javax.swing.JTextField direccionMACDispositivo;
    private javax.swing.JComboBox<String> dispositivoDestino;
    private javax.swing.JComboBox<String> dispositivoOrigen;
    private javax.swing.JButton enviarM;
    private javax.swing.JComboBox<String> estandarRed;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea mensajeEnviar;
    private javax.swing.JTextField nombreDispositivo;
    private javax.swing.JTextField nombreRed;
    private javax.swing.JComboBox<String> redDestino;
    private javax.swing.JComboBox<String> redOrigen;
    private javax.swing.JComboBox<String> redVisualizar;
    private javax.swing.JComboBox<String> redesDisponibles;
    private javax.swing.JComboBox<String> tipoDispositivo;
    private javax.swing.JTextField transmisionRed;
    private javax.swing.JComboBox<String> velocidadRed;
    private javax.swing.JList<String> verDispositivos;
    private javax.swing.JList<String> verRedes;
    private javax.swing.JList<String> vernodo;
    private javax.swing.JButton visualizarDispositivos;
    private javax.swing.JButton visualizarRedes;
    // End of variables declaration//GEN-END:variables
}
